### ISSUE TITLE
Have `zapier convert` take full advantage of zapier-platform-legacy-scripting-runner

### ISSUE THREAD

**Issue by BrunoBernardino** [zapier/zapier-platform-cli#180]
Things that are supported by [`zapier-platform-legacy-scripting-runner`](https://github.com/zapier/zapier-platform-legacy-scripting-runner) that aren't yet being taken advantage of in `zapier convert`:

- [x] Generating different `create` `makeRequest` code based on finding scripting method combinations. (#181)
- [x] Generating different `auth` code based on finding scripting method combinations (for OAuth, and transversely, `get_connection_label`). (#185)
- [x] Generating different `search` `getList` code based on finding scripting method combinations. (#186)
- [x] Generating different `create`/`search` `inputFields` code based on finding scripting method combinations. (#196)
- [x] Generating different `trigger`/`create`/`search` `outputFields` code based on finding scripting method combinations. (#199)
- [x] Generating code in `beforeRequest` for `Basic Auth` when the fields aren't simply username/password (generating "custom" auth instead, and adding a header like API Key does) — great app to try out: 80444. (#200)
- [x] Supporting selectively excluding `inputFields` from `bundle.inputData` in `create`s that don't have `_write` nor `_pre_write` scripting, where the fields have `send_in_json=False` (in WB, these fields weren't included, and in the current conversion they are) (#204)
- [ ] Supporting selectively choosing variables for `scripting.js` HEADER section only when necessary.
- [ ] Support selectively choosing dependencies for `package.json` only when necessary.
- [x] Generating code for `searchOrCreate`s. (#207)
- [x] Replace variables in URLs before sending requests (#208)

**Comment by xavdid** [comment]
I don't have context here but I'm going to assume work on the converter is under control
